### ISSUE TITLE
Side nav and breadcrumbs

### ISSUE THREAD

**Issue by sheri-thomson** [sheri-thomson/ecommerce-pattern-library#13]
@mackenzierose

Hi Mackenzie, I'm sure you have your plate full but if you have time, I wondered if you could take a look at my side-nav and breadcrumbs. For some reason, it isn't showing up in my pattern library but when I inspect the element it's there. I tried changing the colour to see if that was the issue but it didn't seem to do anything. Ironically enough, in my 'mind body' section, the paragraph colour wasn't changing in my pattern library but did in the live site. So I'm wondering if there is a disconnect in the pattern library.

If you're unable to take a look, I totally understand; just let me know :) I was trying not to flood Thomas with my inquiries..

**Comment by sheri-thomson** [comment]
Weird - it works now :/

**Comment by MacKenzieRose** [comment]
Glad it's working! 

If you have problems again, feel free to tag me! :)
