### ISSUE TITLE
footer

### ISSUE THREAD

**Issue by sheri-thomson** [sheri-thomson/ecommerce-pattern-library#14]
@thomasjbradley

Hi Thomas,

On my products page, the footer is displaying differently and I can't figure out why :(

**Comment by thomasjbradley** [comment]
It might be because the `<a>` tags aren’t closed on these lines:
https://github.com/sheri-thomson/ecommerce-pattern-library/blob/master/_patterns/sections/side-nav.html#L4-L7

**Comment by sheri-thomson** [comment]
Thank you!
