### ISSUE TITLE
Button

### ISSUE THREAD

**Issue by sheri-thomson** [sheri-thomson/ecommerce-pattern-library#3]
@thomasjbradley

The style button isn't showing in my pattern library.
I can see the blue underlined link but the css isn't applying to it

**Comment by thomasjbradley** [comment]
There’s code missing at the top of the `main.css` file:
https://github.com/sheri-thomson/ecommerce-pattern-library/blob/master/css/main.css#L1-L2

There should be 2 lines of triple dashes—right at the top, like:

```
---
---
```

**Comment by sheri-thomson** [comment]
It worked! Thank you :)
